---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: istio-reddit
  namespace: istio-reddit
  annotations:
    fluxcd.io/tag.comment: semver:~1.0
    fluxcd.io/tag.post: semver:~1.0
    fluxcd.io/tag.ui: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  releaseName: istio-reddit
  chart:
    git: git@github.com:DmitryShomrin/progon-hw
    ref: master
    path: charts/reddit
  values:
    ui:
      image:
        repository: dmitryshomrin/ui
        tag: 1.0.4
    post:
      image:
        repository: dmitryshomrin/post
        tag: 1.0.5
    comment:
      image:
        repository: dmitryshomrin/comment
        tag: 1.0.0
