---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: istio-reddit
  namespace: istio-reddit
  annotations:
    fluxcd.io/tag.comment: semver:~0.1
    fluxcd.io/tag.post: semver:~0.1
    fluxcd.io/tag.ui: glob:0.1.2
    # fluxcd.io/automated: 'true'
spec:
  releaseName: istio-reddit
  chart:
    git: git@github.com:DmitryShomrin/progon-hw
    ref: master
    path: charts/reddit
  values:
    ui:
      image:
        repository: czm41k/ui
        tag: 0.1.2
    post:
      image:
        repository: czm41k/post
        tag: 0.1.1
    comment:
      image:
        repository: czm41k/comment
        tag: 0.1.1
